title: Practical D2T 2024
description: The 2nd Workshop on Practical LLM-assisted Data-to-Text Generation
show_downloads: false
google_analytics:
theme: minimal-mistakes-jekyll #jekyll-theme-hacker
exclude:
  - script/
